version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
  python: circleci/python@2.1.1

workflows:
  build-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.$CIRCLE_BUILD_NUM
          update-description: true
          deploy: true
          path: ./src
