version: 2.1
jobs:
  test-build-publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Set and persist variable
          command: |
            echo 'export TAG="0.1.${CIRCLE_BUILD_NUM}"' >> /home/circleci/.bashrc
            source /home/circleci/.bashrc
            echo $TAG
      - run:
          name: Run pytest tests
          command: |
            pytest src | tee -a test-results/test-output
      - store_test_results:
          path: test-results/test-output
      - run:
          name: Build get-spotify-popularity container
          command: |
            docker build -t jamesgeddes/itsbeginningtolookalotlikechristmas:$TAG -f src/Dockerfile .
      - deploy:
          name: Push image to Docker Hub
          background: true
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push jamesgeddes/itsbeginningtolookalotlikechristmas:$TAG


workflows:
  version: 2
  main-web:
    jobs:
      - test-build-publish:
          context:
            - org-global
